#!/bin/bash

prg=./try

for t in Test/Test_* ; do
    echo ${t##*/}
    source $t/inp 2>&1 >$t/exp # generate expected output
    $prg <$t/inp 2>&1 >$t/out # generate actual output
    
    # compare the output with the expected output
    if diff -q -w $t/exp $t/out 2>&1 >/dev/null; then
        echo "PASSED" # if output matches expected output
    else
        echo "FAILED" >&2 # if output does not match expected output
    fi
    echo ""
done